---
apiVersion: gitkube.sh/v1alpha1
kind: Remote
metadata:
  creationTimestamp: null
  name: gitkube-ex1-app1
  namespace: default
spec:
  authorizedKeys:
  - |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFe8KMor4iexfKP1GN+TbU7CHTmWDQw5EZ/V4n6+CiHZky5YaegqFYz0KzT4VlUF6horNEGlCIxK5sUtIs44QAT2/S5ehf9Y1O6/lAy22VDmSXIYjj85lQixvFiIW/6OH51O6VxUmddnREMGAhsUsnZQVmmNiJ9ERmY1bCkb/5BJobiuaW5r+zuYxK0GxsmEg6p7N7U3RqYMQe+cF2UPH8PRE4kOE4yOETJh4/0dHXDItFFvhexDUblvilwxyGPuMRwphhBoE4DE8JP1Kzjnhx0O1UTJecd/AmwWLt0aMUBNsDWcWjJBVeOXtaemi+sjwVGPJ4ZB7oIwqoJ9l9w/lX sunfmin@FeliMac.local
  deployments:
  - containers:
    - dockerfile: app1/Dockerfile
      name: app1
      path: ./
    name: gitkube-ex1-app1
  manifests:
    helm: {}
    path: ""
  registry:
    credentials:
      secretKeyRef:
        key: ""
      secretRef: gitkube-ex1-regsecret
    url: registry.theplant-dev.com/sunfmin
status:
  remoteUrl: ""
  remoteUrlDesc: ""
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: gitkube-ex1-app1
  name: gitkube-ex1-app1
  namespace: default
spec:
  selector:
    matchLabels:
      run: gitkube-ex1-app1
  template:
    metadata:
      labels:
        run: gitkube-ex1-app1
    spec:
      imagePullSecrets:
      - name: gitkube-ex1-regsecret
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: app1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: gitkube-ex1-app1
  name: gitkube-ex1-app1
  namespace: default
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    run: gitkube-ex1-app1
  type: LoadBalancer
